### ISSUE TITLE
Codable support

### ISSUE THREAD

**Issue by Strobocop** [JosephDuffy/Partial#128]
This is a great library and a super useful type...so thanks for your work on this! 

One thing that would make this even more useful would be Codable support. I could see using this on the server side for patch updates. I admittedly haven't done a ton of research on the implementation of Partial yet, but wanted to get the conversation going. Do you see this being possible to implement Codable support? Guessing it my require a custom decoder/encoder or use of reflection due to the dynamic nature of the API. Wouldn't mind pitching in on this, but not sure if I would be on a wild goose chase and hitting limitations with Codable.

**Comment by JosephDuffy** [comment]
Sorry for the delay replying here @Strobocop. This sort of thing is something that I've been thinking about since I started work on this.

I've never come up with a way to make this work, although if you have some ideas I'd love to hear them.

The best I can come up with is a way to apply a `Partial` to a `KeyedEncodingContainer`. This would require some sort of method to map a `CodingKey` to a `KeyPath`. I think this would require a few tight constraints, along the lines of:

```swift
protocol KeyPathCodingKeyMapper {
  associatedtype Wrapped
  func codingKeyForKeyPath<Value: Codable, Key: CodingKey>(_ keyPath: KeyPath<Wrapped, Codable>) -> Key?
}

// ... inside Partial
func encode<Key: CodingKey>(to container: KeyedEncodingContainer<Key>, keyPathCodingKeyMapper: KeyPathCodingKeyMapper) {
  // Here we would loop over the stored keys, but how could you know that `Value` is `Codable`?
}
```

This is where I get stuck.

I've thought about updating some of the internals to support applying a `Partial` instance to a `Wrapped` instance by storing key paths that are `WritableKeyPath` (in this case it could be for `KeyPath`s with a `Value` that's `Codable`) but when you look at the internals the values are stored as `[PartialKeyPath<Wrapped>: Any]`.

Note that the `Value` is not known and the value is stored as `Any`.  Storing for example `[KeyPath<Wrapped, Codable>: Any]` would not be possible so this is where I get stuck with this idea.

**Comment by randomeizer** [comment]
How do you guys see `Codable` support working in this context exactly? Is it just mirroring the final 'unwrapped' value, or the partial values?

It's hard to guarantee that every given KeyPath will be Codable, but I guess it could just encode those which are?

Either way, I had a thought on how to get `Value` from a `PartialKeyPath<Wrapped>` value, namely:

```lua

protocol EncodableKeyPath {
    var rootType: Any.Type { get }
    var valueType: Encodable.Type { get }
}

extension KeyPath: EncodableKeyPath where Value: Encodable {
    var rootType: Any.Type { Root.self }

    var valueType: Encodable.Type { Value.self }
}
```

Looping through the internal values, you could do this:

```lua
for (keyPath: value) in values.enumerated() {
    guard let encodableKeyPath = keyPath as? EncodableKeyPath,
          let encodableValue = value as? Encodable,
          let codingKey = mapper.codingKeyForKeyPath(encodableKeyPath)
    else {
        throw Error.uncodableKeyPath(keyPath)
    }
    // encode the value...
    try container.encode(encodableValue, forKey: codingKey)
}
```

How would you see the `KeyPathCodingKeyMapper` getting initialised/passed around?

**Comment by JosephDuffy** [comment]
I played around with this again recently and feel like I have some ideas but nothing that works yet.

Conforming `Partial` to `Encodable`/`Decodable` seems to be impossible. The `KeyPath`/`CodingKey` mapper can't map for a `KeyPath` to a `CodingKey` because the return type (something conforming to `CodingKey`) can't be known. This may have been the easiest to implement, but also the least useful so I'm not too concerned about this.

I think the only possible solution to this is to create new coders, i.e. `PartialEncoder` and `PartialDecoder`. I've never done this before though.

From the research I've done it looks like it'll be easiest to have the new coders use another coder e.g. `JSONEncoder` for the "heavy lifting" of producing and consuming `Data`.

For decoding the values a mapper should be enough if it provides:

```swift
func keyPath<CodingKey: Swift.CodingKey>(for codingKey: CodingKey) -> PartialKeyPath<Self>?
```

I've not got any ideas for how to make encoding work (I don't know how to get the types working for `let codingKey = mapper.codingKeyForKeyPath(encodableKeyPath)`).

I will revisit this with a fresh mind again and see how far I can get.

**Comment by randomeizer** [comment]
Yeah, I had a play too, but couldn't come up with anything. Looked into using `Mirror` to work through available properties on the `Wrapped` type, but it's missing type information there too.

**Comment by JosephDuffy** [comment]
> How do you guys see `Codable` support working in this context exactly? Is it just mirroring the final 'unwrapped' value, or the partial values?

For this there are a couple of different ways it could be useful (if actually possible):

- Encode/decode a `Partial` instance
  - This enables a new feature: storing `Partial` instances e.g. for during a signup flow
- Decode a value of type `Wrapped` using a `Partial` instance
  - This would be better alternative to `PartialConvertible` 

I don't think encoding a value of type `Wrapped` into a `Partial` is possible or useful.

At one point I created an `init(wrapping:)` initialiser that would allow an instance to fallback to and existing value but I never added it because I thought it might be confusing and would be better suited as a separate `Mutable` type.
